/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_User;

/**
 *
 * @author revan
 */
public class panelSR2 extends javax.swing.JPanel {
    panelSR pn1;
    /**
     * Creates new form panelSR
     */
    public panelSR2(panelSR pn1) {
        this.pn1 = pn1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNIM = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonMainPage = new javax.swing.JButton();
        buttonPenghuni = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        buttonCari = new javax.swing.JButton();
        fieldCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCari = new javax.swing.JTable();
        labelCari = new javax.swing.JLabel();
        labelCariPenghuni = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(720, 560));
        setPreferredSize(new java.awt.Dimension(720, 560));

        jPanel1.setBackground(new java.awt.Color(194, 140, 83));
        jPanel1.setMaximumSize(new java.awt.Dimension(190, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(190, 322));

        labelNIM.setForeground(new java.awt.Color(255, 255, 255));
        labelNIM.setText("NIM");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teknik Informatika");

        buttonMainPage.setBackground(new java.awt.Color(116, 62, 0));
        buttonMainPage.setForeground(new java.awt.Color(255, 255, 255));
        buttonMainPage.setText("Main Page");
        buttonMainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainPageActionPerformed(evt);
            }
        });

        buttonPenghuni.setBackground(new java.awt.Color(173, 92, 0));
        buttonPenghuni.setForeground(new java.awt.Color(255, 255, 255));
        buttonPenghuni.setText("Penghuni");
        buttonPenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenghuniActionPerformed(evt);
            }
        });

        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("M Iqbal Revantama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNIM)
                            .addComponent(jLabel6)
                            .addComponent(labelNama))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(buttonPenghuni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMainPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelNama)
                .addGap(18, 18, 18)
                .addComponent(labelNIM)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(116, 116, 116)
                .addComponent(buttonMainPage)
                .addGap(18, 18, 18)
                .addComponent(buttonPenghuni)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(548, 560));

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        tableCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kamar", "No. Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCari);

        labelCari.setText("Hasil Pencarian");

        labelCariPenghuni.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelCariPenghuni.setForeground(new java.awt.Color(116, 62, 0));
        labelCariPenghuni.setText("Cari Penghuni");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCariPenghuni)
                    .addComponent(labelCari)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelCariPenghuni)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCari))
                .addGap(28, 28, 28)
                .addComponent(labelCari)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainPageActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_buttonMainPageActionPerformed

    private void buttonPenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPenghuniActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
    }//GEN-LAST:event_buttonPenghuniActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonMainPage;
    private javax.swing.JButton buttonPenghuni;
    private javax.swing.JTextField fieldCari;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCari;
    private javax.swing.JLabel labelCariPenghuni;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JTable tableCari;
    // End of variables declaration//GEN-END:variables
}
