/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_User;

import java.util.ArrayList;
import java.util.HashMap;
import pengguna.penghuniSR;
import pengguna.user;

/**
 *
 * @author revan
 */
public class panelIdentitas extends javax.swing.JFrame {
    ArrayList <user> identitas_penghuni;
    /**
     * Creates new form panelIdentitas
     */
    public panelIdentitas() {
        initComponents();
    }
    
    public panelIdentitas(user penghuni){
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.isiNama.setText(penghuni.getNama());
        this.isiNIM.setText(penghuni.getID());
        this.isiEmail.setText(penghuni.getEmail());
        this.isiNoTelp.setText(penghuni.getNoTelp());
        if(!penghuni.getID().contains("AD")){
            this.isiJK.setText(((penghuniSR)penghuni).getJK());
            this.isiTgl.setText(((penghuniSR)penghuni).getTglLahir());
            this.isiKamar.setText(((penghuniSR)penghuni).getNoRuang());
            this.isiAlamat.setText(((penghuniSR)penghuni).getJalan() + ", " + ((penghuniSR)penghuni).getKota() +", "+ ((penghuniSR)penghuni).getProv());
        
        this.isiPenyakit.setText(((penghuniSR)penghuni).getPenyakit().toString());
        }
        
    }
    
    public panelIdentitas(ArrayList<user> identitas, int i) {
        this.identitas_penghuni = identitas;
        initComponents();
        
        setLocationRelativeTo(null);
        
        this.isiNama.setText(this.identitas_penghuni.get(i).getNama());
        this.isiNIM.setText(this.identitas_penghuni.get(i).getID());
        this.isiJK.setText(((penghuniSR)this.identitas_penghuni.get(i)).getJK());
        this.isiTgl.setText(((penghuniSR)this.identitas_penghuni.get(i)).getTglLahir());
        this.isiKamar.setText(((penghuniSR)this.identitas_penghuni.get(i)).getNoRuang());
        this.isiAlamat.setText(((penghuniSR)this.identitas_penghuni.get(i)).getJalan() + ", " + ((penghuniSR)this.identitas_penghuni.get(i)).getKota() +", "+ ((penghuniSR)this.identitas_penghuni.get(i)).getProv());
        this.isiEmail.setText(this.identitas_penghuni.get(i).getEmail());
        this.isiNoTelp.setText(this.identitas_penghuni.get(i).getNoTelp());
        this.isiPenyakit.setText(((penghuniSR)this.identitas_penghuni.get(i)).getPenyakit().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isiNama = new javax.swing.JLabel();
        isiNIM = new javax.swing.JLabel();
        isiJK = new javax.swing.JLabel();
        isiTgl = new javax.swing.JLabel();
        isiKamar = new javax.swing.JLabel();
        isiEmail = new javax.swing.JLabel();
        isiNoTelp = new javax.swing.JLabel();
        isiAlamat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        isiPenyakit = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelNama.setText("Nama:");

        jLabel2.setText("NIM :");

        jLabel3.setText("Telp Ortu:");

        jLabel4.setText("Kamar :");

        jLabel5.setText("Jenis Kelamin:");

        jLabel6.setText("Tanggal Lahir :");

        jLabel7.setText("E-mail");

        jLabel8.setText("Alamat: ");

        isiNama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiNama.setText("Nama:");

        isiNIM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiNIM.setText("Nama:");

        isiJK.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiJK.setText("Nama:");

        isiTgl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiTgl.setText("Nama:");

        isiKamar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiKamar.setText("Nama:");

        isiEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiEmail.setText("Nama:");

        isiNoTelp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiNoTelp.setText("Nama:");

        isiAlamat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiAlamat.setText("Nama:");

        jLabel9.setText("Riwayat Penyakit:");

        isiPenyakit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        isiPenyakit.setText("Nama:");

        jPanel2.setBackground(new java.awt.Color(194, 140, 83));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Identitas Penghuni");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(194, 140, 83));

        buttonOK.setBackground(new java.awt.Color(116, 62, 0));
        buttonOK.setForeground(new java.awt.Color(255, 255, 255));
        buttonOK.setText("OK");
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(buttonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(buttonOK)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(isiAlamat)
                    .addComponent(isiNoTelp)
                    .addComponent(isiEmail)
                    .addComponent(isiKamar)
                    .addComponent(isiTgl)
                    .addComponent(isiJK)
                    .addComponent(isiNIM)
                    .addComponent(isiNama)
                    .addComponent(isiPenyakit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNama)
                    .addComponent(isiNama))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(isiNIM))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(isiJK))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(isiTgl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isiKamar))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(isiEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isiNoTelp))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(isiAlamat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(isiPenyakit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelIdentitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelIdentitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelIdentitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelIdentitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelIdentitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private javax.swing.JLabel isiAlamat;
    private javax.swing.JLabel isiEmail;
    private javax.swing.JLabel isiJK;
    private javax.swing.JLabel isiKamar;
    private javax.swing.JLabel isiNIM;
    private javax.swing.JLabel isiNama;
    private javax.swing.JLabel isiNoTelp;
    private javax.swing.JLabel isiPenyakit;
    private javax.swing.JLabel isiTgl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelNama;
    // End of variables declaration//GEN-END:variables
}
