/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_User;

import DAO.DAOuser;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import pengguna.user;

/**
 *
 * @author revan
 */
public class panelSR extends javax.swing.JPanel {
    Connection con;
    user pengguna;
    panelSR2 pn2;
    /**
     * Creates new form panelSR
     */
    public panelSR() {
        initComponents();
    }
    
    public panelSR(Connection con, user pengguna, panelSR2 pn2) {
        this.con = con;
        this.pengguna = pengguna;
        this.pn2 = pn2;
        initComponents();
        this.labelNama.setText(this.pengguna.getNama());
        this.labelNIM.setText(this.pengguna.getID());
        
        this.tampilTabelTutor(this.con, this.pengguna);
        this.tampilTabelBina(this.con, this.pengguna);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelNIM = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonMainPage = new javax.swing.JButton();
        buttonPenghuni = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTutor = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableBina = new javax.swing.JTable();
        labelBina = new javax.swing.JLabel();
        labelMainPage = new javax.swing.JLabel();
        labelJadwalTutor = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(720, 560));
        setPreferredSize(new java.awt.Dimension(720, 560));

        jPanel1.setBackground(new java.awt.Color(194, 140, 83));
        jPanel1.setMaximumSize(new java.awt.Dimension(190, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(190, 322));

        labelNIM.setForeground(new java.awt.Color(255, 255, 255));
        labelNIM.setText("NIM");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Teknik Informatika");

        buttonMainPage.setBackground(new java.awt.Color(173, 92, 0));
        buttonMainPage.setForeground(new java.awt.Color(255, 255, 255));
        buttonMainPage.setText("Main Page");
        buttonMainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMainPageActionPerformed(evt);
            }
        });

        buttonPenghuni.setBackground(new java.awt.Color(116, 62, 0));
        buttonPenghuni.setForeground(new java.awt.Color(255, 255, 255));
        buttonPenghuni.setText("Penghuni");
        buttonPenghuni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPenghuniActionPerformed(evt);
            }
        });

        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setText("M Iqbal Revantama");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNIM)
                            .addComponent(jLabel6)
                            .addComponent(labelNama))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(buttonPenghuni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonMainPage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(labelNama)
                .addGap(18, 18, 18)
                .addComponent(labelNIM)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(116, 116, 116)
                .addComponent(buttonMainPage)
                .addGap(18, 18, 18)
                .addComponent(buttonPenghuni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(548, 560));

        tableTutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mata Kuliah", "Jadwal", "ID kelas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTutor);

        tableBina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Kamar", "No. Telp"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableBina);

        labelBina.setText("Anggota JR Binaan");

        labelMainPage.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelMainPage.setForeground(new java.awt.Color(116, 62, 0));
        labelMainPage.setText("Main Page");

        labelJadwalTutor.setText("Jadwal Tutorial");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMainPage)
                    .addComponent(labelJadwalTutor)
                    .addComponent(labelBina)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelMainPage)
                .addGap(44, 44, 44)
                .addComponent(labelJadwalTutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(labelBina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMainPageActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        
    }//GEN-LAST:event_buttonMainPageActionPerformed

    private void buttonPenghuniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPenghuniActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_buttonPenghuniActionPerformed

    private void tampilTabelTutor(Connection con, user pengguna){
        DAOuser dao = new DAOuser(this.con, this.pengguna);
        ResultSet rs = dao.tampilTutorialSR();
        
        DefaultTableModel model= (DefaultTableModel) this.tableTutor.getModel();
        try {
            while(rs.next()){
                Object[]obj ={rs.getString("matakuliah"), rs.getString("jadwal"), rs.getString("id_kelas")};
                
                model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelSR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void tampilTabelBina(Connection con, user pengguna){
        DAOuser dao = new DAOuser(this.con, this.pengguna);
        ResultSet rs = dao.tampilBinaanSR();
        
        DefaultTableModel model= (DefaultTableModel) this.tableBina.getModel();
        try {
            while(rs.next()){
                Object[]obj ={rs.getString("nama"), rs.getString("no_ruangan"), rs.getString("no_telp")};
                
                model.addRow(obj);
            }
        } catch (SQLException ex) {
            Logger.getLogger(panelSR.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMainPage;
    private javax.swing.JButton buttonPenghuni;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBina;
    private javax.swing.JLabel labelJadwalTutor;
    private javax.swing.JLabel labelMainPage;
    private javax.swing.JLabel labelNIM;
    private javax.swing.JLabel labelNama;
    private javax.swing.JTable tableBina;
    private javax.swing.JTable tableTutor;
    // End of variables declaration//GEN-END:variables
}
